version: "3.7"

services:
    backend:
        build: 
            args:
                user: app
                uid: 1001
            context: ./backend
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: backend
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes: 
            - ./backend:/var/www/html
        depends_on:
            - db
        networks: 
            - app-network

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - app-network
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports: 
            - 8000:80
        links:
            - backend
        volumes: 
            - ./backend:/var/www/html
            - ./setup/nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network

    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: usuario
        ports:
            - 3306:3306
        volumes: 
            - ./setup/data:/var/lib/mysql
        networks:
            - app-network
      
    phpmyadmin:
        container_name: phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - app-network

networks:
  app-network:
    driver: bridge
